### PR TITLE
Ex 02

### PR DESCRIPTION
**Pull request by pkhetland**
Added the coursework for Ex 02. Looking forward to getting a review.

### CODE REVIEW

**Review by ahmedalbuni — CHANGES_REQUESTED** [review]
it seems that there are some merge issues in file_stats.py, please fix it asap so I can review it

**Comment by pkhetland** [comment]
I will fix it ASAP when I get home from work. Thanks for reviewing!

**Review by ahmedalbuni — APPROVED** [review]
Good job!

**Comment by pkhetland** [comment]
Thanks!

**Pull request merged**
